spring:
  application:
    name: cicloestrella
  datasource:
    url: jdbc:postgresql://localhost:5432/cicloestrella_db
    username: root
    password: toor
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
  mvc:
    servlet:
      path: /api
  sql:
    init:
      mode: always
      platform: postgres
      encoding: UTF-8
      data-locations: classpath:/db/import.sql

logging:
  file:
    name: logs/cicloestrella.log
  level:
    root: INFO
    com.example.cicloestrella: DEBUG
  pattern:
    dateformat: "yyyy-MM-dd HH:mm:ss"
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"

application:
  security:
    jwt:
      secret-key : $2a$12$CI2IKB6ygwpxndKPjmXwHuVV1vWsQYippxuxYVB0YUPMeak1vX.9u
      expiration: 3600000 # 1 hora en milisegundos
      refresh-token:
        expiration: 86400000 # 24 horas en milisegundos
